### PR TITLE
Blacklist ubuntu-advantage-tools

### LINKED ISSUE #463: Blacklist ubuntu-advantage-tools
This package is installed by default in Ubuntu, but it seems to be useful only for servers and enterprise deployments, and not very useful for desktop systems. Removing this package can decrease bloat and reduce the size of the operating system.

This is the source code: https://github.com/canonical/ubuntu-advantage-client

The packagename is `ubuntu-advantage-tools`.

### PR DESCRIPTION
**Pull request by jepotter1-archive**
Fixes elementary/os#463.

@cassidyjames

### CODE REVIEW

**Review by danirabbit — CHANGES_REQUESTED** [review]
Let's keep these in alphabetical order please :)

**Comment by jepotter1-archive** [comment]
@danrabbit Done.

**Comment by danirabbit** [comment]
Actually, testing removing this package locally, it removes `ubuntu-minimal`. So, I think before we can do this we need to either:
a. Account for everything in Ubuntu minimal ourselves and not depend on that
b. Ask upstream to make `ubuntu-advantage-tools` a recommends instead of depends

**Comment by jepotter1-archive** [comment]
@danrabbit Thanks for testing it out. I'll go ahead and make a PR sometime later that replaces `ubuntu-minimal` with a custom package set. That way all Ubuntu bloat can be avoided!

**Pull request closed without merging**
