### PR TITLE
Desktop: Install Pipewire

### PR DESCRIPTION
**Pull request by danirabbit**
Drafting to experiment with Pipewire

This probably also needs changes to systemd _somewhere_. I had to:
```
systemctl --user --now disable pulseaudio.service pulseaudio.socket
systemctl --user --now enable pipewire pipewire-pulse
```

### CODE REVIEW

**Comment by danirabbit** [comment]
For reference: https://ubuntuhandbook.org/index.php/2022/04/pipewire-replace-pulseaudio-ubuntu-2204/

**Comment by danirabbit** [comment]
Pipewire is default in Ubuntu since 22.10 so we probably don't need this anymore

**Comment by danirabbit** [comment]
Reopening since it seems we don’t actually have pipewire by default automatically.

relevant commits from xubuntu seeds for reference:

https://github.com/Xubuntu/xubuntu-seed/commit/2a137409b7c3533c59becbc97a776ac7650e7aac

https://github.com/Xubuntu/xubuntu-seed/commit/9f3cad2d35d6e1635f025169c2904ae1af0c47f7

**Review by danirabbit — COMMENTED** [review]
I can’t approve my PR but I think you can approve it @vjr haha

**Review by vjr — APPROVED** [review]
LGTM even if it's my own commit :-)

**Pull request merged**
